---
title: 'CHeck 1,2,3'
author: 'Josh'
output:
  github_document:
    html_preview: true
---


```{r setup postgresql connection, include = FALSE}
library(dplyr)
library(ggplot2)
library(DescTools)
library(RPostgreSQL)

pg = dbDriver("PostgreSQL")
con = dbConnect(pg, user="postgres", password="Vivamus1431!!",
                 host="localhost", port=5432, dbname="bls")

unem <- dbGetQuery(con, "SELECT * FROM state_unemployment")
part <- dbGetQuery(con, "SELECT * FROM state_labor_participation")
wages <- dbGetQuery(con, "SELECT * FROM private_wages")


unem <- unem %>% select(state=area_text,year,period,unem = value)
part <- part %>% select(state=area_text,year,period,part = value)
wages <- wages %>% select(state=state_name,year,period,wages = value)


data <- unem %>% inner_join(part, by=c('state','year','period'))
data <- data %>% inner_join(wages, by=c('state','year','period'))


data$month <- substr(data$period,2,3)
data$date <- paste(data$year,data$month,'01',sep='-')
data$date <- as.Date(data$date)
```

```{r look at rates, echo = FALSE}
data2 <- subset(data,  year >= 2019)
data2$unem <- as.numeric(data2$unem)
data2 <- data2 %>% arrange(state,date) %>% group_by(state) %>% mutate(perc_change = (unem/lag(unem)-1))

check <- subset(data2, date == '2020-04-01')
check <- check %>% ungroup() %>% mutate(rank = rank(-perc_change)) %>% arrange(rank)
sample <- check %>% filter(rank <= 10)
sample2 <- check %>% filter(rank >= 41)


ggplot(check, aes(x=perc_change,y=part)) + geom_point()


ggplot(data2, aes(x=as.Date(date),y=perc_change, colour=state,group=state)) + geom_line()
```

test test test

* * *
